### ISSUE TITLE
Add test cases xyDataCreator

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/convert-to-jcamp#30]
@jobo322 Please add testcases for xyDataCreator (so `xyDataCreator.test.js` in `utils/__tests__`

Should be a simple case with '1,2,3,4,3,2,1,0,-1,-2' and expect the string to obtain

**Comment by lpatiny** [comment]
In fact you should just repeat the test cases from the paper

![image](https://user-images.githubusercontent.com/1484241/143572418-d3200a42-b7ff-4b72-a35c-96a08000298e.png)

**Comment by jobo322** [comment]
it is done 1885a0b623641d619ff1f7ee2db28936bdf0ece1
