### ISSUE TITLE
xy-normalizer

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/convert-to-jcamp#4]
@maasencioh 

xyConvert( object, options={}) 

Please could you make a new project that will normalize xy array whatever is the input

[ [x,y],  [x,y],  [x,y],  [x,y],  [x,y], ]

[ [x,x,x,x], [y,y,y,y,]]

[ {x:, y:}, {x:, y:}, {x:, y:}, {x:, y:}, {x:, y:}, {x:, y:}, ]

{x:[x,x,x,x,x,x,x], y:[y,y,y,y,y,y,y,y]}

I have the 4th kind and would like to create a jcamp. Like that your method can accept a little bit anything.

const {
  format
} = options;

The format is detected automatically except in the case

[ [1,2], [2,3] ] that is ambiguous. It throws an error if format is unspecified

Format are static defined in this library

**Comment by maasencioh** [comment]
@lpatiny this should be added in which organization?

**Comment by lpatiny** [comment]
Good question. Could be mljs

**Comment by maasencioh** [comment]
https://github.com/mljs/xy-convert
