### ISSUE TITLE
XYdata and difdup

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/convert-to-jcamp#46]
there is a trick when you are using difdup compression about the last point that needs to be repeated on the next line. Not sure it was calculated here and you should check the specifications.

![image](https://user-images.githubusercontent.com/1484241/180807068-fcd3843a-f8d7-47e1-9057-f20ddf38a765.png)

![image](https://user-images.githubusercontent.com/1484241/180806995-9254fecb-9f93-4d1a-a96d-779ce210dfee.png)

**Comment by jobo322** [comment]
@lpatiny do you mean it is missing?

**Comment by jobo322** [comment]
@lpatiny seems it is done [here](https://github.com/cheminfo/convert-to-jcamp/blob/master/src/utils/vectorEncoder.ts#L234-L237)

**Comment by lpatiny** [comment]
Ok well possible. If the parser can read the generated jcamp and you recover the same number of points it should be ok.

It could also check that the parsed values are similar. Easy to make a mistake with those factors.

**Comment by jobo322** [comment]
@lpatiny, do you know if it applies only for DIFDUP or we could generalize it?

also, it could be applied for 2D NMR variables, in this [part of code](https://github.com/cheminfo/convert-to-jcamp/blob/47-xydata-and-x-values/src/from2DNMRVariables.ts#L140-L167)?

**Comment by lpatiny** [comment]
Based on this publication: http://old.iupac.org/jcamp/protocols/dxir01.pdf

![image](https://user-images.githubusercontent.com/1484241/183300048-2b02ea5e-1fde-4071-9f62-d934eb091115.png)


Based on this publication: http://www.jcamp-dx.org/protocols/dxnmr01.pdf


This is also quite interesting

![image](https://user-images.githubusercontent.com/1484241/183299957-496df640-738b-4ee4-8e20-6115f6181c49.png)

Even if today I would rather consider 2**24 and not 2**16 as range.

**Comment by lpatiny** [comment]
@jobo322 please close this issue if you think it is ok.

**Comment by jobo322** [comment]
It is included directly in the encoder. I will create a new ticket for recommended ordinate scaling
