### ISSUE TITLE
XYData and X values

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/convert-to-jcamp#47]
I think we could have always for X a value between 0 and Nb points

![image](https://user-images.githubusercontent.com/1484241/180807904-41265ccd-9d96-444a-80e3-77e5b9978111.png)

similar to what bruker generates

**Comment by jobo322** [comment]
@lpatiny Should this change only apply for ntuples?

**Comment by lpatiny** [comment]
It can make sense for any XYData in fact, not only in case of ntuples but I think it is less important in the other cases.
