### ISSUE TITLE
release 1.0.0 and update doc

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/convert-to-jcamp#5]
@maasencioh 

Now that this project depends of xy-parser the documentation should be updated and we should release 1.0.0.

I can then use it in molecular-formula project

**Comment by maasencioh** [comment]
[xy-parser](https://github.com/cheminfo-js/xy-parser) is a converter from text to xy array, I just use `ml-xy-convert` in #3 so when you agree I can publish it

**Comment by maasencioh** [comment]
done in 190415c923472ee98097b1c26ebbf42b85ebab83
