### ISSUE TITLE
Improve from1DNMRVariables

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/convert-to-jcamp#81]
It is not clear what is required and what is not. What is required should not be optional parameters and because it ends up in ##. or ##$ it should be in the corresponding parameters info or meta.

I would like to create a JCAMP-DX file using something like or even simpler if possible.

```
  const xy = signalsToXY(signals, { frequency });
  const data = {
    x: {
      data: xy.x,
      label: 'Chemical Shift (ppm)',
    },
    y: {
      data: xy.y,
    },
  };
  const jcamp = from1DNMRVariables(data, {
    xyEncoding: 'DIFDUP',
    info: {
      title: '1H NMR',
      dataType: 'NMR Spectrum',
    },
    meta: {
      '.OBSERVE FREQUENCY': frequency
  });
```

**Comment by jobo322** [comment]
@lpatiny in the type `MeasurementXYVariables` the property `label` is mandatory, looking in your example, do you prefer it to be optional?

**Comment by jobo322** [comment]
I suggest this

```
const data = {
      x: {
        data: xy.x,
        label: 'Chemical Shift (ppm)',
      },
      r: {
        data: xy.y,
        label: 'Real data',
      },
    };
    const jcamp = from1DNMRVariables(data, {
      xyEncoding: 'DIFDUP',
      info: {
        title: '1H NMR',
        dataType: 'NMR Spectrum',
        '.OBSERVE FREQUENCY': frequency,
      },
    });
    ```

we need to manage the possibility of complex data. so { x, r } and { x, r, i }

**Comment by jobo322** [comment]
it was done by 
- https://github.com/cheminfo/convert-to-jcamp/pull/82

exposed in the version 5.4.11
